// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "b2c4a399-1a33-456a-b67a-fccfbad767df");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1577070079);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1577070199);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1577078207);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1577069839);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1577069719);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1577069959);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1576735792);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1577070319);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{502bb218-8604-4208-aa5e-fd9fb1bb70b7}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575954000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1577080457008");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1577082260008");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1577078649237");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1577082249237");
user_pref("browser.search.cohort", "nov17-2");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181209160329");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1576008148");
user_pref("browser.startup.homepage_override.buildID", "20181209160329");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yahoo");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "a33065f3fc034a078a2b90de8a650980");
user_pref("extensions.blocklist.lastModified", "Fri, 20 Dec 2019 22:42:36 GMT");
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1577070079);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181209160329");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"e2af03e8-daa9-41ac-9af2-9310e8fda72b\",\"screenshots@mozilla.org\":\"4e77b171-83ad-4de8-88df-2fb38ecd86cd\",\"webcompat-reporter@mozilla.org\":\"05c2b34b-3400-452a-a7d7-a0738f971d65\",\"webcompat@mozilla.org\":\"dd1e6797-996e-48eb-bf46-8911fde0b253\",\"baidu-code-update@mozillaonline.com\":\"dcb7bc5e-a74e-4107-a841-0b990efb37e8\",\"fxmonitor@mozilla.org\":\"fe2cd835-8940-4194-a5f4-865cb6223ca7\"}");
user_pref("idle.lastDailyNotification", 1577070242);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1576008262);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181209160329");
user_pref("media.gmp-manager.lastCheck", 1577067398);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1577070242);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4d7b1c9b-2f6e-468f-9846-324db7cdfae2");
user_pref("security.sandbox.plugin.tempDirSuffix", "049f073e-4e7e-4beb-afb1-63b92c01295c");
user_pref("services.blocklist.addons.checked", 1577069943);
user_pref("services.blocklist.gfx.checked", 1577069943);
user_pref("services.blocklist.onecrl.checked", 1577069943);
user_pref("services.blocklist.pinning.checked", 1577069943);
user_pref("services.blocklist.plugins.checked", 1577069943);
user_pref("services.settings.clock_skew_seconds", 15);
user_pref("services.settings.last_update_seconds", 1577069943);
user_pref("services.settings.main.language-dictionaries.last_check", 1577069943);
user_pref("services.settings.main.sites-classification.last_check", 1577069943);
user_pref("services.settings.main.tippytop.last_check", 1577069943);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1577070242);
user_pref("toolkit.startup.last_success", 1577402024);
user_pref("toolkit.telemetry.cachedClientID", "e6f9af8e-8a93-4188-a055-f6afae0d3343");
user_pref("toolkit.telemetry.previousBuildID", "20181209160329");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
